{% set name = "stream-zip" %}
{% set version = "0.0.68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stream_zip-{{ version }}.tar.gz
  sha256: db2a318d0108617bcf99fed027848c4e2a3bc2368bce22cab5a27525aa55fb21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.7
    - hatchling
    - pip
  run:
    - python >=3.6.7

test:
  imports:
    - stream_zip
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python function to construct a ZIP archive with stream processing - without having to store the entire ZIP in memory or disk
  home: https://github.com/uktrade/stream-zip
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michalc
